### ISSUE TITLE
what dll dependencies it need to run on windows10 python3.9

### ISSUE THREAD

**Issue by zhusihan-python** [andreaschiavinato/python_grabber#15]
hi, i install python_grabber on windows 10, here is the error when run then demo code:
Traceback (most recent call last):
  File "E:\projects\NeatSvtScan\scan\camera.py", line 222, in <module>
    from pygrabber.dshow_graph import FilterGraph
  File "D:\softwares\conda\envs\qt5\lib\site-packages\pygrabber\dshow_graph.py", line 35, in <module>
    from pygrabber.windows_media import *
  File "D:\softwares\conda\envs\qt5\lib\site-packages\pygrabber\windows_media.py", line 220, in <module>
    WMCreateProfileManager = windll.Wmvcore.WMCreateProfileManager
  File "D:\softwares\conda\envs\qt5\lib\ctypes\__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "D:\softwares\conda\envs\qt5\lib\ctypes\__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] parameter error
![image](https://user-images.githubusercontent.com/23504604/144989037-ab0aa71e-6cb0-4d64-b870-278c50f9306c.png)
my python version is 3.9.0
i don't know if its a bug on win10 or just some dll dependencies are missing

**Comment by zhusihan-python** [comment]
i found that the WMVCORE.DLL didn't missing, and when run in adminostrator account, it turns out without this error. maybe a priviledge problem or system path not setting well? kind of werid
